# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ygor.gallina
email: ygor.gallina@univ-nantes.fr
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ygorg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ygorg
profile_picture: assets/portrait.jpg
# Build settings
#theme: minima
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-last-modified-at  # Not supported anymore by github

social_links:
  github:  ygorg

links:
  -
    title: github
    url: http://github.com/ygorg

papers:
  -
    title: "Redefining Absent Keyphrases and their Effect on Retrieval Effectiveness."
    url: "https://arxiv.org/pdf/2103.12440.pdf"
    link: "https://github.com/boudinfl/redefining-absent-keyphrases"
    authors: "Florian Boudin, and Ygor Gallina."
    journal: "2019 Conference of the North American Chapter of the Association for Computational Linguistics (NAACL-HTL)"
    date: "Jun. 2021"
  -
    title: "Large-Scale Evaluation of Keyphrase Extraction Models."
    url: "https://hal.archives-ouvertes.fr/hal-02878953"
    link: "https://github.com/ygorg/JCDL_2020_KPE_Eval"
    authors: "Ygor Gallina, Florian Boudin, and Béatrice Daille."
    journal: "ACM/IEEE Joint Conference on Digital Libraries (JCDL)"
    date: "Aug. 2020"
  -
    title: "Keyphrase Generation for Scientific Document Retrieval."
    url: "https://hal.archives-ouvertes.fr/hal-02556086"
    link: "https://github.com/boudinfl/ir-using-kg"
    authors: "Florian Boudin, Ygor Gallina, and Akiko Aizawa."
    journal: "58th Annual Meeting of the Association for Computational Linguistics (ACL)"
    date: "Jul. 2020"
  -
    title: "KPTimes: A Large-Scale Dataset for Keyphrase Generation on News Documents."
    url: "https://hal.archives-ouvertes.fr/hal-02395709"
    link: "https://github.com/ygorg/KPTimes"
    authors: "Ygor Gallina, Florian Boudin, and Béatrice Daille."
    journal: "12th International Conference on Natural Language Generation (INLG)"
    date: "Oct. 2019"
  -
    title: "State of the art of deep learning methods for automatic keyphrase extraction."
    url: "https://hal.archives-ouvertes.fr/hal-02395693"
    authors: "Ygor Gallina."
    journal: "21e Rencontre des Étudiants Chercheurs en Informatique pour le Traitement Automatique des Langues (RECITAL)"
    date: "Jul. 2019"
  -
    title: "DeFT 2019 : Auto-encodeurs, Gradient Boosting et combinaisons de modèles pour l’identification automatique de mots-clés."
    url: "http://hal.univ-nantes.fr/hal-02433723"
    authors: "Mérième Bouhandi, Florian Boudin, and Ygor Gallina."
    journal: "Défi Fouille de Textes (DEFT)"
    date: "Jul. 2019"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
